apiVersion: v1
data:
  admin-password: UmNVamZyUHVDODRRSnYwWHdnQ0tROGZXRFZ6TnZ2WWU0RktyOWV1RA==
  admin-user: YWRtaW4=
  ldap-toml: ''
kind: Secret
metadata:
  labels:
    app.kapicorp.dev/component: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.4.0
    helm.sh/chart: grafana-8.8.2
  name: grafana
  namespace: grafana
type: Opaque
